config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stores
  get "listing" => "products#listing"
  
  post "new" => "registrations#create", as: :create_registration
  get "me" => "registrations#me"
  post "sign_in" => "registrations#sign_in"

  resources :products, only: [:index, :new, :create, :show, :edit, :update]

  scope :buyers do
    resources :orders, only: [:index, :create, :update, :destroy, :show]
  end  
 
  resources :stores do
    get 'products', to: 'products#products_by_store'
    get "/orders/new" => "stores#new_order"
  end 


  # Defines the root path route ("/")
  # root "posts#index"
  root to: "welcome#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  has_many :orders, through: :order_items

  validates :title, presence: true
  validates :price, presence: true
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_forgery_protection
  before_action :authenticate!  

    def listing
        if !current_user.admin?
            redirect_to root_path, notice: "No permission for you!"
        end
        @products = Product.includes(:store)
    end

    def index
      if current_user.admin? 
        @products = Product.includes(:store)
      else
        @products = current_user.stores.includes(:products).flat_map(&:products)
      end

      respond_to do |format|
        format.html
        format.json { render json: @products }
      end
    end   
    
    def new
      @product = Product.new

      if current_user.admin?
        @stores = Store.all
      else
        @stores = current_user.stores
      end
    end

    def show
      @product = Product.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: @product }
      end
    end

    def create
      @product = Product.new(product_params)
  
      if @product.save
        redirect_to product_path(@product), notice: 'Product was successfully created.'
      else
        render :new
      end
    end

    def edit
      @product = Product.find(params[:id])
      if current_user.admin?
        @stores = Store.all
      else
        @stores = current_user.stores
      end      
    end    

    def update
      @product = Product.find(params[:id])
    
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to product_path(@product), notice: 'Product was successfully updated.' }
          format.json { render json: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # def products_by_store
    #   @store = Store.find(params[:store_id])
    #   if current_user.admin? || current_user.stores.include?(@store)
    #     @products = @store.products
    #   else
    #     redirect_to root_path, notice: "No permission for you!"
    #   end

    #   respond_to do |format|
    #     format.html
    #     # format.json { render json: @products }        
    #     format.json { render json: { store: @store, products: @products } }
    #   end
    # end

    def products_by_store
      @store = Store.find(params[:store_id])
      if current_user.admin? || current_user.buyer? || current_user.stores.include?(@store)
        @products = @store.products
      else
        redirect_to root_path, notice: "No permission for you!"
      end
    
      respond_to do |format|
        format.html
        format.json { render json: { store: @store, products: @products } }
      end
    end
  
    
    private
  
    def product_params
      params.require(:product).permit(:title, :price, :store_id)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
 
 <div class="field">
  <%= form.label :store_id, "Store" %>
  <%= text_field_tag :store_name, @product.store.name, readonly: true %>
  <%= form.hidden_field :store_id, value: @product.store_id %>
</div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding-top: 10px;
  padding-bottom: 20px;
  padding-left: 30px;
  padding-right: 40px;
}
</style>

<h1>Listing Products</h1>

<%= link_to 'New Product', new_product_path %>

<br>&nbsp;

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Product</th>
      <th>Price</th>
      <th>Store</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% if current_user.admin? || product.store.user == current_user %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.title %></td>
          <td><%= number_to_currency(product.price) %></td>
          <td>
            <%= link_to "#{product.store.name} (Store id:#{product.store.id})", store_products_path(product.store) %>
          </td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/products/listing.html.erb
<h1>Products Listing</h1>

<div>
    <% @products.each do |product| %>
        <div>
            <h3>
                <%= product.title %>
                <%= number_to_currency(product.price, unit: "R$ ", separator: ",", delimiter: ".") %>
            </h3>
           
            <p>Store: <%= product.store.name %>
        </div>
        <hr>
    <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with(model: @product, local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </p>

  <p>
    <%= form.label :store_id, "Store" %><br>
    <%= form.collection_select :store_id, @stores, :id, :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/products/products_by_store.html.erb
<h1>Products in <%= @store.name %></h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.title, product_path(product) %>
      - <%= number_to_currency(product.price) %>
    </li>
  <% end %>
</ul>

<br>
<%= link_to 'Back to Stores', stores_path %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Store:</strong>
  <%= @product.store.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>